module: KeyboardShortcuts
github_url: https://github.com/sindresorhus/KeyboardShortcuts
root_url: https://sindresorhus.com/KeyboardShortcuts
copyright: MIT License © [Sindre Sorhus](https://sindresorhus.com)
swift_build_tool: spm
build_tool_arguments:
  - '-Xswiftc'
  - '-swift-version'
  - '-Xswiftc'
  - '5'
theme: fullwidth
hide_documentation_coverage: true
head: "
  <script>
  window.addEventListener('DOMContentLoaded', () => {
    document.querySelector('.header-link[href^=dash-feed]').remove();
  });
  </script>
"
